name: sebha
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # Add additional dependencies here, if needed
  # Example:
  # provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^3.0.0

  # Add additional dev dependencies here, if needed
  # Example:
  # mockito: ^5.0.17

# For more information on the Dart part of this file, see:
# https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  # Define the assets used in your application.
  assets:
    - assets/images/
    # Add more asset directories or specific files if needed
    # Example:
    # - assets/images/logo.png

  # Define custom fonts here, if you have any.
  fonts:
     
    - family: arabicfonts
      fonts:
        - asset: assets/fonts/KOUFIBD.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/DTHULUTH.ttf
          weight: 700
          style: normal
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
